In [4]:
import pandas as pd               
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score

In [2]:
dataset=pd.read_csv("train-titanic.csv")

In [3]:
le=preprocessing.LabelEncoder()

In [5]:
dataset["Sex"]=le.fit_transform(dataset["Sex"])

In [6]:
dataset["Embarked"]=le.fit_transform(dataset["Embarked"])

In [7]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2

In [8]:
from sklearn import svm

In [9]:
X=dataset.drop(["Pclass","PassengerId","Name","Ticket","Cabin"],axis=1)

In [10]:
X.head()

Survived  Sex   Age  SibSp  Parch     Fare  Embarked
0         0    1  22.0      1      0   7.2500         2
1         1    0  38.0      1      0  71.2833         0
2         1    0  26.0      0      0   7.9250         2
3         1    0  35.0      1      0  53.1000         2
4         0    1  35.0      0      0   8.0500         2

In [11]:
y=dataset["Pclass"]

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [13]:
svm_m = svm.SVC(gamma=0.01,C=100)

In [14]:
svm_m.fit(X_train,y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [15]:
y_pred=svm_m.predict(X_test)

In [16]:
ac=accuracy_score(y_test,y_pred)

In [17]:
print(ac)

0.9026217228464419


In [38]:
confusion_matrix(y_test,y_pred)

array([[ 64,   4,   2],
       [  4,  36,   9],
       [  1,   6, 141]], dtype=int64)

In [40]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2

# Assignment Section

Checking the accuracy score for the dataset with different dependent variables.

In [66]:

# creating a function
import numpy as np
def svm_a(i):
    a1=[]
    b1=[]
    for features in i:
        y = dataset[features]
        X = dataset.drop([features,"PassengerId","Name","Ticket","Cabin"],axis=1)
        X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
        from sklearn import svm
        from sklearn.metrics import accuracy_score,confusion_matrix
        clf = svm.SVC(gamma=0.01,C=100)
        y_pred = clf.fit(X_train,y_train).predict(X_test)
        Acc_value = accuracy_score(y_test,y_pred,normalize=True)
        a1.append(Acc_value)
    return a1


def svm_c(i):
    a1=[]
    b1=[]
    for features in i:
        y = dataset[features]
        X = dataset.drop([features,"PassengerId","Name","Ticket","Cabin"],axis=1)
        X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
        from sklearn import svm
        from sklearn.metrics import accuracy_score,confusion_matrix
        clf = svm.SVC(gamma=0.01,C=100)
        y_pred = clf.fit(X_train,y_train).predict(X_test)  
        conf_mat = confusion_matrix(y_test,y_pred)
        b1.append(conf_mat)
    return b1

i= ["Survived","Sex","Embarked","Parch","SibSp"]
Accuracy_score = np.array(svm_a(i))
Conf_mat=np.array(svm_c(i))

print(Accuracy_score)
print(Conf_mat)


[0.74157303 0.72659176 0.76779026 0.79775281 0.74906367]
[array([[124,  33],
       [ 36,  74]], dtype=int64)
 array([[ 66,  32],
       [ 41, 128]], dtype=int64)
 array([[ 23,   2,  24],
       [  0,   8,  14],
       [ 18,   4, 174]], dtype=int64)
 array([[187,   6,   5,   0,   0,   0],
       [ 21,  15,   3,   0,   0,   1],
       [ 10,   6,  11,   0,   0,   0],
       [  0,   0,   1,   0,   0,   0],
       [  1,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0]], dtype=int64)
 array([[150,  24,   7,   0,   1,   0,   0],
       [ 21,  39,   5,   0,   0,   0,   0],
       [  4,   1,   3,   0,   0,   0,   0],
       [  0,   2,   1,   3,   1,   0,   0],
       [  0,   0,   0,   0,   2,   0,   0],
       [  0,   0,   0,   0,   0,   1,   0],
       [  0,   0,   0,   0,   0,   0,   2]], dtype=int64)]


In [76]:
df=pd.DataFrame(i,index=range(0,5))

In [78]:
df["Accuracy score"]=pd.DataFrame(Accuracy_score)

In [81]:
df["confusion Matrix"]=pd.DataFrame(Conf_mat)

In [82]:
df.head()

0  Accuracy score                                   confusion Matrix
0  Survived        0.741573                              [[124, 33], [36, 74]]
1       Sex        0.726592                              [[66, 32], [41, 128]]
2  Embarked        0.767790            [[23, 2, 24], [0, 8, 14], [18, 4, 174]]
3     Parch        0.797753  [[187, 6, 5, 0, 0, 0], [21, 15, 3, 0, 0, 1], [...
4     SibSp        0.749064  [[150, 24, 7, 0, 1, 0, 0], [21, 39, 5, 0, 0, 0...

# Conclusion

from the above table we can say that Parch feature has highest accuracy score among all the featues in the dataset.