# 1. Create a 3x3x3 array with random values 

In [4]:
import numpy as np

a1 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]],[[111,222,333],[444,555,666],[777,888,999]]])
print(a1)
a1.shape

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 11  22  33]
  [ 44  55  66]
  [ 77  88  99]]

 [[111 222 333]
  [444 555 666]
  [777 888 999]]]


(3, 3, 3)

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [26]:
import numpy as np

a2= np.zeros((5,5))
a2[1,0]=1
a2[2,1]=2
a2[3,2]=3
a2[4,3]=4
print(a2)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]
5


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [31]:
import numpy as np

a3= np.zeros((8,8))
for i in range(a3.shape[1]):
    for j in range(a3.shape[1]):
        if ((i+j)%2 == 0):
            a3[i][j]= 1
        
print(a3)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# 4. Normalize a 5x5 random matrix

In [46]:
a4= np.random.random((3,3))

print(a4)
dmax = a4.max()
dmin = a4.min()
a4 = (a4 - dmin)/(dmax - dmin)

print("\n\n",a4)

[[0.4939864  0.9828013  0.73167178]
 [0.66557018 0.92860295 0.44944831]
 [0.23285805 0.87918393 0.49408909]]


 [[0.34819748 1.         0.66513531]
 [0.57699317 0.92773006 0.28880886]
 [0.         0.86183306 0.34833441]]


# 5.  How to find common values between two arrays?

In [54]:
a5 = np.array([7,8,9])
a6 =np.array([9,10,7])
for i in a5.flatten():
    if i in a6.flatten():
        print(i)

7
9


# 6.How to get the dates of yesterday, today and tomorrow?

In [55]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print("Yestraday's Date: ",yesterday)
today     = np.datetime64('today')
print("Today's Date: ",today)
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("Tomorrow's Date: ",tomorrow)

Yestraday's Date:  2020-07-26
Today's Date:  2020-07-27
Tomorrow's Date:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [61]:
A = np.random.random((2,2))
B = np.random.random((2,2))
print((A==B).all()) # The whole array or matrix comparison
print(A==B) # Element-wise comparison

False
[[False False]
 [False False]]


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [62]:
a7 = np.random.random(10)
print(a7)
print(a7.max())
for i in range(len(a7)):
    if a7[i] == a7.max():
        a7[i] = 0
        break
print(a7)

[0.58666791 0.65237451 0.77784482 0.08035887 0.8836623  0.54293384
 0.98869112 0.66272045 0.81100354 0.48631775]
0.9886911179163205
[0.58666791 0.65237451 0.77784482 0.08035887 0.8836623  0.54293384
 0.         0.66272045 0.81100354 0.48631775]


# 9. How to print all the values of an array?

In [67]:
a8=np.random.random((3,3))
for i in range(len(a8)):
    for j in range(len(a8)):
        print(a8[i][j])

0.7989869458299313
0.9271894333262499
0.3052796782731726
0.030813341548783013
0.9922571738241428
0.6705131387993613
0.11318538556879432
0.3716455308418021
0.11001072709269655


# 10.Subtract the mean of each row of a matrix

In [71]:
import scipy
from scipy import stats
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
m = []

print("\n\n\n",a)

for i in range(a.shape[0]):
    b = np.array(a[i])
    m.append(np.mean(a[i]))
o = np.ones_like(a)
for i in range(o.shape[0]):
    o[i] = o[i]*m[i]
print("\n\n\nThe list of means of each row: \n",m)
print("\n\n\nOnes like a multiplied by the mean of the row: \n", o)
print("\n\n\n The resulting matrix is: \n",a-o)





 [[1 2 3]
 [4 5 6]
 [7 8 9]]



The list of means of each row: 
 [2.0, 5.0, 8.0]



Ones like a multiplied by the mean of the row: 
 [[2 2 2]
 [5 5 5]
 [8 8 8]]



 The resulting matrix is: 
 [[-1  0  1]
 [-1  0  1]
 [-1  0  1]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [72]:
v = [2,4,6,8,10]

V = np.random.randint(1,100,20)
print(V)
for i in v:
    V[i] = V[i]+1
print(V)

[46 14 68 62 23  9 86 24 75 71 14 90 14 95 31 17 77  8  4 44]
[46 14 69 62 24  9 87 24 76 71 15 90 14 95 31 17 77  8  4 44]


# 12.How to get the diagonal of a dot product?

In [78]:
q = np.random.random((2,2))
r = np.random.random((2,2))
s = q.dot(r)
l=[]
for i in range(s.shape[0]):
    for j in range(s.shape[1]):
        if i ==j:
            l.append(s[i][j])
print("The diagonal elements of the dot product are: ",l)

The diagonal elements of the dot product are:  [0.675679894352838, 0.1850034820692046]


# 13.How to find the most frequent value in an array?

In [76]:
from scipy import stats

a = np.random.randint(1,20,25)
print(a)
m = stats.mode(a)
print(m)

[ 1 15 18 18 12 11 11  8 18  4 12  6  1 11 16  9 12  2 19  1  5 12 17 13
 16]
ModeResult(mode=array([12]), count=array([4]))


# 14.How to get the n largest values of an array

In [75]:
t = np.random.randint(1,10000,1000)
n = int(input("Please enter the number of largest value's you want to see?"))
print ((t[np.argsort(t)[-n:]])[::-1])

Please enter the number of largest value's you want to see?10
[9978 9971 9963 9953 9947 9944 9940 9918 9911 9909]


# 15.How to create a record array from a regular array?

In [77]:
a1=np.array([10,20,30,40])
a2=np.array(['Orange','Grape','Banana','Apple'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3])
print(result)

[(10, 'Orange', 12.2) (20, 'Grape', 15. ) (30, 'Banana', 20. )
 (40, 'Apple', 40. )]
